# -*- coding: utf-8 -*-

import pygame
from pygame.locals import *

#CONSTANTES

pygame.display.init()

FPS = 60

RESOLUCION = [pygame.display.Info().current_w,  pygame.display.Info().current_h]

ANCHO_PANTALLA = RESOLUCION[0]
ALTO_PANTALLA = RESOLUCION[1]

ANCHO_XOGO = ANCHO_PANTALLA * 4
ALTO_XOGO = ALTO_PANTALLA * 2

REL_CADROS_PANTALLA = 50

NUM_CADROS_ANCHO_PANTALLA = int(REL_CADROS_PANTALLA * (ANCHO_PANTALLA/float(ALTO_PANTALLA)))
NUM_CADROS_ALTO_PANTALLA = REL_CADROS_PANTALLA

NUM_CADROS_ANCHO_XOGO = NUM_CADROS_ANCHO_PANTALLA * ANCHO_XOGO/ANCHO_PANTALLA
NUM_CADROS_ALTO_XOGO = NUM_CADROS_ALTO_PANTALLA * ALTO_XOGO/ALTO_PANTALLA

ANCHO_CADRO = ANCHO_PANTALLA / float(NUM_CADROS_ANCHO_PANTALLA)
ALTO_CADRO = ALTO_PANTALLA / float(NUM_CADROS_ALTO_PANTALLA)

MARCO_LATERAL = 0
MARCO_VERTICAL = 0
